spring:
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Configuration Mail (Bien alignée sous spring:)
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:elmouktadirmohamed@gmail.com}
    password: ${MAIL_PASSWORD:xbbmdisdjsdeblvn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Tes topics Kafka (Désindentés car ils ne sont pas sous spring:)
kafka:
  topics:
    notification-otp: notification.otp
    notification-transaction-success: notification.transaction.success
    notification-transaction-failed: notification.transaction.failed
    notification-beneficiary-added: notification.beneficiary.added
  topic:
    registred-notif-event: new-user-registred
    email-virified-notif-event: email-verified
    resend-verified-code-notif-event: resend-verification-code
    forgot-password-notif-event: forgot-password

---
# PROFIL DEVELOPPEMENT
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/notification_db}
    username: ${DB_USERNAME:notification_user}
    password: ${DB_PASSWORD:notification_pass}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8085

---
# PROFIL PRODUCTION
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-service-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

server:
  port: 8085