# Example secrets file - DO NOT COMMIT ACTUAL SECRETS
# Create actual secrets using kubectl:
# kubectl create secret generic auth-service-secrets --from-literal=db-url='...' --from-literal=db-username='...' --from-literal=db-password='...' --from-literal=jwt-secret='...' -n ebank

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: ebank
type: Opaque
stringData:
  db-url: "jdbc:postgresql://your-cloud-db:5432/auth_db" # TODO: Replace
  db-username: "your-username" # TODO: Replace
  db-password: "your-password" # TODO: Replace
  jwt-secret: "your-jwt-secret-min-256-bits" # TODO: Replace

---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: ebank
type: Opaque
stringData:
  db-url: "jdbc:postgresql://your-cloud-db:5432/user_db" # TODO: Replace
  db-username: "your-username" # TODO: Replace
  db-password: "your-password" # TODO: Replace

---
apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
  namespace: ebank
type: Opaque
stringData:
  db-url: "jdbc:postgresql://your-cloud-db:5432/account_db" # TODO: Replace
  db-username: "your-username" # TODO: Replace
  db-password: "your-password" # TODO: Replace

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: ebank
type: Opaque
stringData:
  db-url: "jdbc:postgresql://your-cloud-db:5432/payment_db" # TODO: Replace
  db-username: "your-username" # TODO: Replace
  db-password: "your-password" # TODO: Replace

---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: ebank
type: Opaque
stringData:
  db-url: "jdbc:postgresql://your-cloud-db:5432/notification_db" # TODO: Replace
  db-username: "your-username" # TODO: Replace
  db-password: "your-password" # TODO: Replace
  mail-username: "your-email@gmail.com" # TODO: Replace
  mail-password: "your-app-password" # TODO: Replace

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: ebank
type: Opaque
stringData:
  client-secret: "your-keycloak-client-secret" # TODO: Replace

