version: '3.8'

services:
  postgres-account:
    image: postgres:16
    container_name: postgres-account
    restart: always
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account
      POSTGRES_PASSWORD: accountpass
    ports:
      - "5433:5432"
    volumes:
      - account_db_data:/var/lib/postgresql/data

#  account-service:
#    build: .
#    container_name: account-service
#    depends_on:
#      - postgres-account
#    ports:
#      - "8082:8082"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-account:5432/account_db
#      SPRING_DATASOURCE_USERNAME: account
#      SPRING_DATASOURCE_PASSWORD: accountpass

volumes:
  account_db_data:
