name: Account Service CI

on:
  push:
    paths:
      - 'account-service/**'
  pull_request:
    paths:
      - 'account-service/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      working-directory: ./account-service
      run: mvn clean package -DskipTests
    
    - name: Run tests
      working-directory: ./account-service
      run: mvn test
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -f Dockerfile.account-service -t ebank/account-service:${{ github.sha }} .
        docker tag ebank/account-service:${{ github.sha }} ebank/account-service:latest
    
    - name: Tag for GHCR
      run: |
        docker tag ebank/account-service:${{ github.sha }} ghcr.io/${{ github.repository }}/account-service:${{ github.sha }}
        docker tag ebank/account-service:${{ github.sha }} ghcr.io/${{ github.repository }}/account-service:latest

    - name: Push to GHCR
      if: github.event_name != 'pull_request'
      run: |
        docker push ghcr.io/${{ github.repository }}/account-service:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/account-service:latest

    # TODO: Add deployment step (CD) - Responsible: Abdelghafour
    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl set image deployment/account-service account-service=ebank/account-service:${{ github.sha }} -n ebank

